import os
import json
from pathlib import Path

COMPOSE_TEMPLATE = """package {package_name}

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable
fun {component_name}(
    modifier: Modifier = Modifier
) {{
    Card(
        modifier = modifier
            .fillMaxWidth()
            .padding(8.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.85f)
        )
    ) {{
        Column(
            modifier = Modifier.padding(16.dp)
        ) {{
            Text(
                text = "{component_name}",
                style = MaterialTheme.typography.titleMedium,
                fontSize = 18.sp
            )
            Spacer(modifier = Modifier.height(8.dp))
            Text(
                text = "Autonomous component scaffold generated by AI Agents Workspace Tools.",
                style = MaterialTheme.typography.bodyMedium
            )
        }}
    }}
}}
"""

REPOSITORY_TEMPLATE = """package {package_name}

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

class {repo_name}Repository {{
    private val _dataFlow = MutableStateFlow<List<String>>(emptyList())
    val dataFlow: StateFlow<List<String>> = _dataFlow.asStateFlow()

    fun updateData(newData: List<String>) {{
        _dataFlow.value = newData
    }}
}}
"""

def scaffold_compose_component(output_file, package_name="com.piuu.launcher.ui.components"):
    path = Path(output_file).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    component_name = path.stem

    content = COMPOSE_TEMPLATE.format(package_name=package_name, component_name=component_name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return str(path)

def scaffold_repository(output_file, package_name="com.piuu.launcher.repository"):
    path = Path(output_file).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    repo_name = path.stem.replace("Repository", "")

    content = REPOSITORY_TEMPLATE.format(package_name=package_name, repo_name=repo_name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return str(path)

def scaffold_extension_template(target_dir, name="Sample Extension", version="1.0.0"):
    dest = Path(target_dir).resolve()
    dest.mkdir(parents=True, exist_ok=True)

    manifest = {
        "id": f"com.piuu.ext.{name.lower().replace(' ', '-')}",
        "name": name,
        "version": version,
        "entryPoint": "index.js",
        "permissions": ["storage", "ui", "telemetry"],
        "author": "Autonomous Agent Developer"
    }

    with open(dest / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    with open(dest / "index.js", "w", encoding="utf-8") as f:
        f.write("// Piuu Launcher Extension Entrypoint\nexport default function init() {\n    console.log('Extension initialized');\n}\n")

    with open(dest / "README.md", "w", encoding="utf-8") as f:
        f.write(f"# {name}\n\nVersion {version} extension bundle.\n")

    return str(dest)
